// <auto-generated />
using System;
using InboxCurator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InboxCurator.Data.Migrations
{
    [DbContext(typeof(InboxCuratorDbContext))]
    [Migration("20260823195011_PinPromptToEvaluationCorpus")]
    partial class PinPromptToEvaluationCorpus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("InboxCurator.Data.ClassifierPromptVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LockedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LockedEvaluationCorpusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputJsonSchema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputSchemaVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemPromptSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LockedEvaluationCorpusId");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("ClassifierPromptVersions", (string)null);
                });

            modelBuilder.Entity("InboxCurator.Data.ClassifierResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassifierRunId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("ClassifierRunProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Confidence")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EvalCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EvalDurationNanoseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EvaluationCorpusItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsColdLoadRequest")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LoadDurationNanoseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PromptEvalCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PromptEvalDurationNanoseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rationale")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonCodesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Recommendation")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<int>("ThinkingCharacterCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ThinkingPresent")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TotalDurationNanoseconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationCorpusItemId");

                    b.HasIndex("ClassifierRunId", "Status");

                    b.HasIndex("ClassifierRunProfileId", "EvaluationCorpusItemId")
                        .IsUnique();

                    b.ToTable("ClassifierResults", (string)null);
                });

            modelBuilder.Entity("InboxCurator.Data.ClassifierRun", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelRequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("ClassifierPromptVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedItems")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentProfileKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentSplit")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("EvaluationCorpusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedItems")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalItems")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassifierPromptVersionId");

                    b.HasIndex("EvaluationCorpusId", "ClassifierPromptVersionId", "Stage");

                    b.ToTable("ClassifierRuns", (string)null);
                });

            modelBuilder.Entity("InboxCurator.Data.ClassifierRunProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassifierRunId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ColdLoadDurationNanoseconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContextLength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExecutionOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeepAlive")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ModelSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("PredominantlyVramResident")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RuntimeContextLength")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SizeVramBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Stream")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<string>("ThinkMode")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassifierRunId", "ProfileKey")
                        .IsUnique();

                    b.ToTable("ClassifierRunProfiles", (string)null);
                });

            modelBuilder.Entity("InboxCurator.Data.ClusterDecision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AppliesToFuture")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CutoffDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupKey")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupKey");

                    b.HasIndex("TargetType", "TargetValue")
                        .IsUnique();

                    b.ToTable("ClusterDecisions", (string)null);
                });

            modelBuilder.Entity("InboxCurator.Data.ClusterDecisionAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AppliesToFuture")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangeKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("ClusterDecisionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CutoffDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchingMessageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClusterDecisionId", "Revision")
                        .IsUnique();

                    b.ToTable("ClusterDecisionAudits", (string)null);
                });

            modelBuilder.Entity("InboxCurator.Data.EvaluationCorpus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("EligibleSourceCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExcludedCleanExistingOnlyCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExcludedCleanOlderThanCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExcludedDeferCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExcludedMissingEvidenceCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SplitStrategy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("EvaluationCorpora", (string)null);
                });

            modelBuilder.Entity("InboxCurator.Data.EvaluationCorpusItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttachmentCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("EvaluationCorpusId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstReceivedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroundTruth")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupKey")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportantCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastReceivedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ListUnsubscribeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PromotionsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelationshipCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RepresentativeSubjectsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Split")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("StarredCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("UnreadCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationCorpusId", "Split");

                    b.HasIndex("EvaluationCorpusId", "TargetType", "TargetValue")
                        .IsUnique();

                    b.ToTable("EvaluationCorpusItems", (string)null);
                });

            modelBuilder.Entity("InboxCurator.Data.MessageRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GmailMessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupDisplay")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupKey")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasAttachment")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasDirectCorrespondence")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasListUnsubscribe")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasThreadInteraction")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IndexedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsImportant")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPromotion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStarred")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUnread")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LabelIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSeenScanId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ListId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedSenderAddress")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplyToAddress")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(998)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DateUtc");

                    b.HasIndex("GmailMessageId")
                        .IsUnique();

                    b.HasIndex("GroupKey");

                    b.HasIndex("ThreadId");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("InboxCurator.Data.ScanCheckpoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActiveRunId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("NextPageToken")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("ProcessedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Kind")
                        .IsUnique();

                    b.ToTable("ScanCheckpoints", (string)null);
                });

            modelBuilder.Entity("InboxCurator.Data.SentInteraction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GmailMessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSeenScanId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientAddress")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipientAddress");

                    b.HasIndex("ThreadId");

                    b.HasIndex("GmailMessageId", "RecipientAddress")
                        .IsUnique();

                    b.ToTable("SentInteractions", (string)null);
                });

            modelBuilder.Entity("InboxCurator.Data.ClassifierPromptVersion", b =>
                {
                    b.HasOne("InboxCurator.Data.EvaluationCorpus", "LockedEvaluationCorpus")
                        .WithMany("LockedPromptVersions")
                        .HasForeignKey("LockedEvaluationCorpusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LockedEvaluationCorpus");
                });

            modelBuilder.Entity("InboxCurator.Data.ClassifierResult", b =>
                {
                    b.HasOne("InboxCurator.Data.ClassifierRun", "ClassifierRun")
                        .WithMany("Results")
                        .HasForeignKey("ClassifierRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InboxCurator.Data.ClassifierRunProfile", "ClassifierRunProfile")
                        .WithMany("Results")
                        .HasForeignKey("ClassifierRunProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InboxCurator.Data.EvaluationCorpusItem", "EvaluationCorpusItem")
                        .WithMany("ClassifierResults")
                        .HasForeignKey("EvaluationCorpusItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassifierRun");

                    b.Navigation("ClassifierRunProfile");

                    b.Navigation("EvaluationCorpusItem");
                });

            modelBuilder.Entity("InboxCurator.Data.ClassifierRun", b =>
                {
                    b.HasOne("InboxCurator.Data.ClassifierPromptVersion", "ClassifierPromptVersion")
                        .WithMany("Runs")
                        .HasForeignKey("ClassifierPromptVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InboxCurator.Data.EvaluationCorpus", "EvaluationCorpus")
                        .WithMany("Runs")
                        .HasForeignKey("EvaluationCorpusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassifierPromptVersion");

                    b.Navigation("EvaluationCorpus");
                });

            modelBuilder.Entity("InboxCurator.Data.ClassifierRunProfile", b =>
                {
                    b.HasOne("InboxCurator.Data.ClassifierRun", "ClassifierRun")
                        .WithMany("Profiles")
                        .HasForeignKey("ClassifierRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassifierRun");
                });

            modelBuilder.Entity("InboxCurator.Data.ClusterDecisionAudit", b =>
                {
                    b.HasOne("InboxCurator.Data.ClusterDecision", "ClusterDecision")
                        .WithMany("AuditEntries")
                        .HasForeignKey("ClusterDecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClusterDecision");
                });

            modelBuilder.Entity("InboxCurator.Data.EvaluationCorpusItem", b =>
                {
                    b.HasOne("InboxCurator.Data.EvaluationCorpus", "EvaluationCorpus")
                        .WithMany("Items")
                        .HasForeignKey("EvaluationCorpusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluationCorpus");
                });

            modelBuilder.Entity("InboxCurator.Data.ClassifierPromptVersion", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("InboxCurator.Data.ClassifierRun", b =>
                {
                    b.Navigation("Profiles");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("InboxCurator.Data.ClassifierRunProfile", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("InboxCurator.Data.ClusterDecision", b =>
                {
                    b.Navigation("AuditEntries");
                });

            modelBuilder.Entity("InboxCurator.Data.EvaluationCorpus", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("LockedPromptVersions");

                    b.Navigation("Runs");
                });

            modelBuilder.Entity("InboxCurator.Data.EvaluationCorpusItem", b =>
                {
                    b.Navigation("ClassifierResults");
                });
#pragma warning restore 612, 618
        }
    }
}
